version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -e .
      - run:
          name: run tests
          command: python test_proj/manage.py test

workflows:
  test:
    jobs:
      - build_and_test
